databases:
  - name: spot_DB
    databaseName: spot_db
    user: spot
    region: singapore

services:
  - type: web
    name: spot
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spot_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
